/**
 * Express server — handles both the API (/api/*, /uploads/*) and serves
 * the Vite-built SPA frontend (.output/public/).
 *
 * Architecture (production / Docker / HuggingFace Spaces):
 *   - All traffic hits this single process on PORT (default 7860).
 *   - /api/*      → Express route handlers → MongoDB
 *   - /uploads/*  → Express static middleware → uploads/ directory
 *   - Everything else → .output/public/ static files
 *   - Unknown paths  → .output/public/index.html  (SPA fallback)
 *
 * Build step (`npm run build`) generates:
 *   .output/public/assets/*.js, *.css   ← Vite client bundle
 *   .output/public/index.html           ← generated by scripts/generate-index.cjs
 */

require('dotenv').config();
const express = require('express');
const path    = require('path');
const cors    = require('cors');
const fs      = require('fs');

const app  = express();
const PORT = parseInt(process.env.PORT || '7860', 10);

// ── Uploads directory ──────────────────────────────────────────────────────
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });

// ── CORS ───────────────────────────────────────────────────────────────────
// In production everything is same-origin; CORS only matters in local dev
// when Vite (port 5173) proxies to this server (port 3001 / 7860).
const allowedOrigin = process.env.CORS_ORIGIN || 'http://localhost:5173';
const corsOptions = allowedOrigin === '*'
  ? { origin: true, credentials: true }
  : { origin: allowedOrigin, credentials: true };
app.use(cors(corsOptions));

app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));

app.use('/uploads', express.static(uploadsDir));

// ── API Routes ─────────────────────────────────────────────────────────────
app.use('/api/auth',       require('./routes/auth.cjs'));
app.use('/api/teachers',   require('./routes/teachers.cjs'));
app.use('/api/students',   require('./routes/students.cjs'));
app.use('/api/attendance', require('./routes/attendance.cjs'));
app.use('/api/grades',     require('./routes/grades.cjs'));
app.use('/api/email',      require('./routes/email.cjs'));

// ── Stats (admin dashboard) ────────────────────────────────────────────────
const { authenticateToken, requireAdmin } = require('./middleware/auth.cjs');
const { Teacher, Student, Attendance, Grade } = require('./database/models.cjs');

app.get('/api/stats', authenticateToken, requireAdmin, async (req, res) => {
  try {
    const [totalTeachers, totalStudents, recentAtt, recentGrades] =
      await Promise.all([
        Teacher.countDocuments(),
        Student.countDocuments(),
        Attendance.find().sort({ createdAt: -1 }).limit(8).populate('student_id', 'name class_name'),
        Grade.find().sort({ createdAt: -1 }).limit(8).populate('student_id', 'name'),
      ]);
    res.json({
      totalTeachers, totalStudents,
      recentAttendance: recentAtt.map(a => ({
        date: a.date, status: a.status,
        student_name: a.student_id?.name       || '—',
        class_name:   a.student_id?.class_name || '—',
      })),
      recentGrades: recentGrades.map(g => ({
        subject: g.subject, exam_type: g.exam_type,
        marks_obtained: g.marks_obtained, total_marks: g.total_marks,
        student_name: g.student_id?.name || '—',
      })),
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── Serve Frontend (Vite SSR build) ───────────────────────────────────────
const staticPublicDir = path.join(__dirname, 'dist', 'client');
const ssrServerPath   = path.join(__dirname, 'dist', 'server', 'server.js');

let ssrHandler = null;

if (fs.existsSync(staticPublicDir)) {
  // Serve built client static files directly
  app.use(express.static(staticPublicDir, { index: false }));
}

if (fs.existsSync(ssrServerPath)) {
  // Dynamically load the ES Module SSR bundle generated by Vite
  import(ssrServerPath)
    .then(m => {
      const ssrApp = m.default || m;
      if (ssrApp && typeof ssrApp.fetch === 'function') {
        ssrHandler = webFetchBridge(ssrApp.fetch);
        console.log('✅  Vite SSR Handler loaded successfully');
      }
    })
    .catch(err => {
      console.error('❌  Failed to load SSR handler:', err);
    });
}

// SSR catch-all fallback
app.get('*', (req, res) => {
  if (ssrHandler) {
    ssrHandler(req, res);
  } else {
    res.status(503).send('<h1>App is starting up…</h1><p>The SSR engine is initializing or not built yet.</p>');
  }
});

/**
 * Bridge a Web-fetch handler `(Request) => Response` to a Node.js
 * `(IncomingMessage, ServerResponse) => void` style middleware.
 */
function webFetchBridge(fetchHandler) {
  return async (req, res) => {
    try {
      const protocol = req.socket.encrypted ? 'https' : 'http';
      const host = req.headers.host || 'localhost';
      const url = `${protocol}://${host}${req.url}`;

      // Collect request body
      const chunks = [];
      for await (const chunk of req) chunks.push(chunk);
      const body = chunks.length > 0 ? Buffer.concat(chunks) : undefined;

      const webRequest = new Request(url, {
        method: req.method,
        headers: req.headers,
        body: body && body.length > 0 ? body : undefined,
        duplex: 'half',
      });

      const webResponse = await fetchHandler(webRequest);

      res.statusCode = webResponse.status;
      for (const [key, value] of webResponse.headers.entries()) {
        res.setHeader(key, value);
      }
      const responseBody = await webResponse.arrayBuffer();
      res.end(Buffer.from(responseBody));
    } catch (err) {
      console.error('SSR fetch bridge error:', err);
      res.statusCode = 500;
      res.end('Internal Server Error');
    }
  };
}

// ── Connect MongoDB then start ─────────────────────────────────────────────
const { connect } = require('./database/db.cjs');

const dbPromise = connect().catch(err => {
  console.error('❌  MongoDB connection failed:', err.message);
  if (require.main === module) process.exit(1);
});

if (require.main === module) {
  dbPromise.then(() => {
    app.listen(PORT, '0.0.0.0', () => {
      console.log(`\n🏫  S.D. Model Sr. Sec. School — Management System`);
      console.log(`🚀  http://0.0.0.0:${PORT}  [${process.env.NODE_ENV || 'development'}]\n`);
    });
  });
}

module.exports = app;
