/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherGradebookRouteImport } from './routes/teacher.gradebook'
import { Route as TeacherComplaintsRouteImport } from './routes/teacher.complaints'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as PublicFacultyRouteImport } from './routes/public.faculty'
import { Route as PublicCalendarRouteImport } from './routes/public.calendar'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGradebookRoute = TeacherGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherComplaintsRoute = TeacherComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const PublicFacultyRoute = PublicFacultyRouteImport.update({
  id: '/public/faculty',
  path: '/public/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCalendarRoute = PublicCalendarRouteImport.update({
  id: '/public/calendar',
  path: '/public/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/public/calendar': typeof PublicCalendarRoute
  '/public/faculty': typeof PublicFacultyRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/complaints': typeof TeacherComplaintsRoute
  '/teacher/gradebook': typeof TeacherGradebookRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/public/calendar': typeof PublicCalendarRoute
  '/public/faculty': typeof PublicFacultyRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/complaints': typeof TeacherComplaintsRoute
  '/teacher/gradebook': typeof TeacherGradebookRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/public/calendar': typeof PublicCalendarRoute
  '/public/faculty': typeof PublicFacultyRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/complaints': typeof TeacherComplaintsRoute
  '/teacher/gradebook': typeof TeacherGradebookRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/profile'
    | '/admin/teachers'
    | '/public/calendar'
    | '/public/faculty'
    | '/teacher/attendance'
    | '/teacher/complaints'
    | '/teacher/gradebook'
    | '/teacher/profile'
    | '/teacher/students'
    | '/admin/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/calendar'
    | '/admin/profile'
    | '/admin/teachers'
    | '/public/calendar'
    | '/public/faculty'
    | '/teacher/attendance'
    | '/teacher/complaints'
    | '/teacher/gradebook'
    | '/teacher/profile'
    | '/teacher/students'
    | '/admin'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/profile'
    | '/admin/teachers'
    | '/public/calendar'
    | '/public/faculty'
    | '/teacher/attendance'
    | '/teacher/complaints'
    | '/teacher/gradebook'
    | '/teacher/profile'
    | '/teacher/students'
    | '/admin/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  PublicCalendarRoute: typeof PublicCalendarRoute
  PublicFacultyRoute: typeof PublicFacultyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/gradebook': {
      id: '/teacher/gradebook'
      path: '/gradebook'
      fullPath: '/teacher/gradebook'
      preLoaderRoute: typeof TeacherGradebookRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/complaints': {
      id: '/teacher/complaints'
      path: '/complaints'
      fullPath: '/teacher/complaints'
      preLoaderRoute: typeof TeacherComplaintsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/public/faculty': {
      id: '/public/faculty'
      path: '/public/faculty'
      fullPath: '/public/faculty'
      preLoaderRoute: typeof PublicFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/calendar': {
      id: '/public/calendar'
      path: '/public/calendar'
      fullPath: '/public/calendar'
      preLoaderRoute: typeof PublicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherComplaintsRoute: typeof TeacherComplaintsRoute
  TeacherGradebookRoute: typeof TeacherGradebookRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherComplaintsRoute: TeacherComplaintsRoute,
  TeacherGradebookRoute: TeacherGradebookRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TeacherRoute: TeacherRouteWithChildren,
  PublicCalendarRoute: PublicCalendarRoute,
  PublicFacultyRoute: PublicFacultyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
